package com.ceiba.cxf.services.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-10-25T12:04:18.058-05:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "CalculadoraImplService",
                  wsdlLocation = "http://localhost:8080/Calculadora?wsdl",
                  targetNamespace = "http://serviceImpl.ceiba.com/")
public class CalculadoraImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://serviceImpl.ceiba.com/", "CalculadoraImplService");
    public final static QName CalculadoraImplPort = new QName("http://serviceImpl.ceiba.com/", "CalculadoraImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Calculadora?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Calculadora?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculadoraImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculadoraImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculadoraImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplPort")
    public Calculadora getCalculadoraImplPort() {
        return super.getPort(CalculadoraImplPort, Calculadora.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImplPort")
    public Calculadora getCalculadoraImplPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraImplPort, Calculadora.class, features);
    }

}
