
package com.ceiba.prueba.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-10-25T12:04:18.003-05:00
 * Generated source version: 3.4.4
 *
 */
public final class Calculadora_CalculadoraImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://serviceImpl.ceiba.com/", "CalculadoraImplService");

    private Calculadora_CalculadoraImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculadoraImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CalculadoraImplService ss = new CalculadoraImplService(wsdlURL, SERVICE_NAME);
        Calculadora  port = ss.getCalculadoraImplPort();

        {
        System.out.println("Invoking suma...");
        double _suma_arg0 = 0.0;
        double _suma_arg1 = 0.0;
        double _suma__return = port.suma(_suma_arg0, _suma_arg1);
        System.out.println("suma.result=" + _suma__return);


        }

        System.exit(0);
    }

}
